import PDFDocument from "pdfkit";

const LEVELS = { 1: "normal", 2: "above normal", 3: "well above normal" };

export function buildPdfReport(record, patient, clinicalRecs = []) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const x = record.inputs;
    const high = record.riskLevel === "high";

    doc.fontSize(18).font("Helvetica-Bold").text("Cardiovascular Disease Prediction Report");
    doc.fontSize(9).font("Helvetica").fillColor("#666")
      .text(`Generated ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC`);
    doc.moveDown();

    section(doc, "Patient");
    line(doc, `Patient ID: ${patient.patientId || "—"}    Research ID: ${patient.anonId || "—"}`);
    line(doc, `Name: ${patient.fullName}    Email: ${patient.email}`);
    line(doc, `Assessment date: ${record.createdAt.toISOString().slice(0, 16).replace("T", " ")} UTC`);
    doc.moveDown(0.5);

    section(doc, "AI Risk Assessment");
    doc.fontSize(13).font("Helvetica-Bold")
      .fillColor(high ? "#dc2626" : record.riskLevel === "medium" ? "#d97706" : "#16a34a")
      .text(`${record.riskLevel.toUpperCase()} RISK — ${(record.riskProbability * 100).toFixed(1)}% probability`);
    doc.fontSize(10).font("Helvetica").fillColor("#000")
      .text(`Alert status: ${record.alertStatus === "high_risk" ? "HIGH RISK — consult a doctor promptly" : "Normal"}`);
    doc.moveDown(0.5);

    section(doc, "Health Information Provided");
    line(doc, `Age: ${x.age_years} years    Gender: ${x.gender === 2 ? "Male" : "Female"}    BMI: ${record.bmi}`);
    line(doc, `Height: ${x.height_cm} cm    Weight: ${x.weight_kg} kg`);
    line(doc, `Blood pressure: ${x.ap_hi}/${x.ap_lo} mmHg    Cholesterol: ${LEVELS[x.cholesterol]}    Glucose: ${LEVELS[x.gluc]}`);
    line(doc, `Medical history: ${[
      x.prior_heart_disease && "prior heart disease",
      x.hypertension_dx && "hypertension",
      x.diabetes && "diabetes",
      x.high_chol_dx && "high cholesterol",
      x.family_history && "family history",
    ].filter(Boolean).join(", ") || "none reported"}`);
    line(doc, `Wearable vitals: HR ${x.resting_hr} bpm, HRV ${x.hrv_ms} ms, SpO2 ${x.spo2}%, RR ${x.resp_rate}/min, Temp ${x.body_temp} C`);
    const ECG_TEXT = ["normal", "ST-T abnormality", "left ventricular hypertrophy"];
    const TMT_TEXT = ["not performed", "negative", "positive (inducible ischemia)"];
    line(doc, `Clinical tests: ECG ${ECG_TEXT[x.ecg_result] || "normal"}; 2D Echo LVEF ${x.lvef ?? "-"}%; ` +
      `TMT ${TMT_TEXT[x.tmt_result] || "not performed"}; CAC score ${Math.round(x.cac_score ?? 0)} Agatston`);
    line(doc, `Lifestyle: ${Math.round(x.daily_steps).toLocaleString()} steps/day, sleep ${x.sleep_hours} h (quality ${x.sleep_quality}/10), stress ${x.stress_level}/10, exercise ${x.exercise_freq} d/wk`);
    line(doc, `Smoker: ${x.smoke ? "yes" : "no"}    Alcohol: ${x.alco ? "yes" : "no"}    Active: ${x.active ? "yes" : "no"}`);
    doc.moveDown(0.5);

    section(doc, "Explanation (SHAP) — Key Contributing Factors");
    for (const item of record.explanation) {
      line(doc, `• ${item.factor}: ${item.direction === "increases_risk" ? "increases risk" : "decreases risk"}`);
    }
    doc.moveDown(0.5);

    if (record.recommendations) {
      const r = record.recommendations;
      section(doc, "Personalized Wellness Recommendations");
      for (const [title, items] of [
        ["Diet", r.diet], ["Exercise", r.exercise], ["Sleep", r.sleep],
        ["Lifestyle", r.lifestyle], ["Daily reminders", r.reminders],
      ]) {
        if (!items?.length) continue;
        doc.fontSize(10).font("Helvetica-Bold").fillColor("#000").text(title);
        items.forEach((t) => line(doc, `• ${t}`));
        doc.moveDown(0.3);
      }
      if (r.follow_up) {
        doc.fontSize(10).font("Helvetica-Bold").fillColor("#dc2626").text(r.follow_up);
        doc.fillColor("#000");
      }
      doc.moveDown(0.5);
    }

    if (record.reviewNote) {
      section(doc, "Clinician Review");
      line(doc, record.reviewNote);
      doc.moveDown(0.5);
    }
    if (clinicalRecs.length) {
      section(doc, "Clinical Recommendations");
      clinicalRecs.forEach((rec) => line(doc, `• ${rec.recommendation}`));
      doc.moveDown(0.5);
    }

    doc.fontSize(8).font("Helvetica-Oblique").fillColor("#666").text(
      "These are general wellness recommendations generated by a machine learning system and do not replace professional medical advice. For high-risk results, consult a doctor promptly."
    );
    doc.end();
  });
}

function section(doc, title) {
  doc.fontSize(12).font("Helvetica-Bold").fillColor("#000").text(title);
  doc.moveDown(0.2);
}

function line(doc, text) {
  doc.fontSize(10).font("Helvetica").fillColor("#222").text(text);
}
